/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CourierRouteImport } from './routes/courier'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as OrganizationRouteImport } from './routes/organization'
import { Route as TenantRouteImport } from './routes/tenant'
import { Route as DsmClientsRouteImport } from './routes/dsm.clients'
import { Route as DsmCookbooksRouteImport } from './routes/dsm.cookbooks'
import { Route as DsmDataBagsRouteImport } from './routes/dsm.data-bags'
import { Route as DsmEnvironmentsRouteImport } from './routes/dsm.environments'
import { Route as DsmPolicyGroupsRouteImport } from './routes/dsm.policy-groups'
import { Route as DsmPolicyfilesRouteImport } from './routes/dsm.policyfiles'
import { Route as DsmRolesRouteImport } from './routes/dsm.roles'
import { Route as NodesIndexRouteImport } from './routes/nodes.index'
import { Route as NodesActivityRouteImport } from './routes/nodes.activity'
import { Route as NodesCohortsRouteImport } from './routes/nodes.cohorts'
import { Route as NodesEnrollRouteImport } from './routes/nodes.enroll'
import { Route as NodesSettingsRouteImport } from './routes/nodes.settings'
import { Route as NodesSkillsRouteImport } from './routes/nodes.skills'
import { Route as ReportingIndexRouteImport } from './routes/reporting/index'
import { Route as DsmNodesIndexRouteImport } from './routes/dsm.nodes.index'
import { Route as DsmNodesNodeIdRouteImport } from './routes/dsm.nodes.$nodeId'
import { Route as NodesDetailNodeIdRouteImport } from './routes/nodes.detail.$nodeId'
import { Route as ReportingClientIndexRouteImport } from './routes/reporting/client.index'
import { Route as ReportingClientRunIdRouteImport } from './routes/reporting/client.$runId'
import { Route as ReportingInspecIndexRouteImport } from './routes/reporting/inspec.index'
import { Route as ReportingInspecScanIdRouteImport } from './routes/reporting/inspec.$scanId'
import { Route as ReportingNodeManagementIndexRouteImport } from './routes/reporting/node-management.index'
import { Route as ReportingNodeManagementNodeIdRouteImport } from './routes/reporting/node-management.$nodeId'
import { Route as ReportingInspecProfileProfileIdRouteImport } from './routes/reporting/inspec.profile.$profileId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourierRoute = CourierRouteImport.update({
  id: '/courier',
  path: '/courier',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationRoute = OrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantRoute = TenantRouteImport.update({
  id: '/tenant',
  path: '/tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const DsmClientsRoute = DsmClientsRouteImport.update({
  id: '/dsm/clients',
  path: '/dsm/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const DsmCookbooksRoute = DsmCookbooksRouteImport.update({
  id: '/dsm/cookbooks',
  path: '/dsm/cookbooks',
  getParentRoute: () => rootRouteImport,
} as any)
const DsmDataBagsRoute = DsmDataBagsRouteImport.update({
  id: '/dsm/data-bags',
  path: '/dsm/data-bags',
  getParentRoute: () => rootRouteImport,
} as any)
const DsmEnvironmentsRoute = DsmEnvironmentsRouteImport.update({
  id: '/dsm/environments',
  path: '/dsm/environments',
  getParentRoute: () => rootRouteImport,
} as any)
const DsmPolicyGroupsRoute = DsmPolicyGroupsRouteImport.update({
  id: '/dsm/policy-groups',
  path: '/dsm/policy-groups',
  getParentRoute: () => rootRouteImport,
} as any)
const DsmPolicyfilesRoute = DsmPolicyfilesRouteImport.update({
  id: '/dsm/policyfiles',
  path: '/dsm/policyfiles',
  getParentRoute: () => rootRouteImport,
} as any)
const DsmRolesRoute = DsmRolesRouteImport.update({
  id: '/dsm/roles',
  path: '/dsm/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesIndexRoute = NodesIndexRouteImport.update({
  id: '/nodes/',
  path: '/nodes/',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesActivityRoute = NodesActivityRouteImport.update({
  id: '/nodes/activity',
  path: '/nodes/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesCohortsRoute = NodesCohortsRouteImport.update({
  id: '/nodes/cohorts',
  path: '/nodes/cohorts',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesEnrollRoute = NodesEnrollRouteImport.update({
  id: '/nodes/enroll',
  path: '/nodes/enroll',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesSettingsRoute = NodesSettingsRouteImport.update({
  id: '/nodes/settings',
  path: '/nodes/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesSkillsRoute = NodesSkillsRouteImport.update({
  id: '/nodes/skills',
  path: '/nodes/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportingIndexRoute = ReportingIndexRouteImport.update({
  id: '/reporting/',
  path: '/reporting/',
  getParentRoute: () => rootRouteImport,
} as any)
const DsmNodesIndexRoute = DsmNodesIndexRouteImport.update({
  id: '/dsm/nodes/',
  path: '/dsm/nodes/',
  getParentRoute: () => rootRouteImport,
} as any)
const DsmNodesNodeIdRoute = DsmNodesNodeIdRouteImport.update({
  id: '/dsm/nodes/$nodeId',
  path: '/dsm/nodes/$nodeId',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesDetailNodeIdRoute = NodesDetailNodeIdRouteImport.update({
  id: '/nodes/detail/$nodeId',
  path: '/nodes/detail/$nodeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportingClientIndexRoute = ReportingClientIndexRouteImport.update({
  id: '/reporting/client/',
  path: '/reporting/client/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportingClientRunIdRoute = ReportingClientRunIdRouteImport.update({
  id: '/reporting/client/$runId',
  path: '/reporting/client/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportingInspecIndexRoute = ReportingInspecIndexRouteImport.update({
  id: '/reporting/inspec/',
  path: '/reporting/inspec/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportingInspecScanIdRoute = ReportingInspecScanIdRouteImport.update({
  id: '/reporting/inspec/$scanId',
  path: '/reporting/inspec/$scanId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportingNodeManagementIndexRoute =
  ReportingNodeManagementIndexRouteImport.update({
    id: '/reporting/node-management/',
    path: '/reporting/node-management/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReportingNodeManagementNodeIdRoute =
  ReportingNodeManagementNodeIdRouteImport.update({
    id: '/reporting/node-management/$nodeId',
    path: '/reporting/node-management/$nodeId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReportingInspecProfileProfileIdRoute =
  ReportingInspecProfileProfileIdRouteImport.update({
    id: '/reporting/inspec/profile/$profileId',
    path: '/reporting/inspec/profile/$profileId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/courier': typeof CourierRoute
  '/downloads': typeof DownloadsRoute
  '/organization': typeof OrganizationRoute
  '/tenant': typeof TenantRoute
  '/dsm/clients': typeof DsmClientsRoute
  '/dsm/cookbooks': typeof DsmCookbooksRoute
  '/dsm/data-bags': typeof DsmDataBagsRoute
  '/dsm/environments': typeof DsmEnvironmentsRoute
  '/dsm/policy-groups': typeof DsmPolicyGroupsRoute
  '/dsm/policyfiles': typeof DsmPolicyfilesRoute
  '/dsm/roles': typeof DsmRolesRoute
  '/nodes/activity': typeof NodesActivityRoute
  '/nodes/cohorts': typeof NodesCohortsRoute
  '/nodes/enroll': typeof NodesEnrollRoute
  '/nodes/settings': typeof NodesSettingsRoute
  '/nodes/skills': typeof NodesSkillsRoute
  '/nodes/': typeof NodesIndexRoute
  '/reporting/': typeof ReportingIndexRoute
  '/dsm/nodes/$nodeId': typeof DsmNodesNodeIdRoute
  '/nodes/detail/$nodeId': typeof NodesDetailNodeIdRoute
  '/reporting/client/$runId': typeof ReportingClientRunIdRoute
  '/reporting/inspec/$scanId': typeof ReportingInspecScanIdRoute
  '/reporting/node-management/$nodeId': typeof ReportingNodeManagementNodeIdRoute
  '/dsm/nodes/': typeof DsmNodesIndexRoute
  '/reporting/client/': typeof ReportingClientIndexRoute
  '/reporting/inspec/': typeof ReportingInspecIndexRoute
  '/reporting/node-management/': typeof ReportingNodeManagementIndexRoute
  '/reporting/inspec/profile/$profileId': typeof ReportingInspecProfileProfileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/courier': typeof CourierRoute
  '/downloads': typeof DownloadsRoute
  '/organization': typeof OrganizationRoute
  '/tenant': typeof TenantRoute
  '/dsm/clients': typeof DsmClientsRoute
  '/dsm/cookbooks': typeof DsmCookbooksRoute
  '/dsm/data-bags': typeof DsmDataBagsRoute
  '/dsm/environments': typeof DsmEnvironmentsRoute
  '/dsm/policy-groups': typeof DsmPolicyGroupsRoute
  '/dsm/policyfiles': typeof DsmPolicyfilesRoute
  '/dsm/roles': typeof DsmRolesRoute
  '/nodes/activity': typeof NodesActivityRoute
  '/nodes/cohorts': typeof NodesCohortsRoute
  '/nodes/enroll': typeof NodesEnrollRoute
  '/nodes/settings': typeof NodesSettingsRoute
  '/nodes/skills': typeof NodesSkillsRoute
  '/nodes': typeof NodesIndexRoute
  '/reporting': typeof ReportingIndexRoute
  '/dsm/nodes/$nodeId': typeof DsmNodesNodeIdRoute
  '/nodes/detail/$nodeId': typeof NodesDetailNodeIdRoute
  '/reporting/client/$runId': typeof ReportingClientRunIdRoute
  '/reporting/inspec/$scanId': typeof ReportingInspecScanIdRoute
  '/reporting/node-management/$nodeId': typeof ReportingNodeManagementNodeIdRoute
  '/dsm/nodes': typeof DsmNodesIndexRoute
  '/reporting/client': typeof ReportingClientIndexRoute
  '/reporting/inspec': typeof ReportingInspecIndexRoute
  '/reporting/node-management': typeof ReportingNodeManagementIndexRoute
  '/reporting/inspec/profile/$profileId': typeof ReportingInspecProfileProfileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/courier': typeof CourierRoute
  '/downloads': typeof DownloadsRoute
  '/organization': typeof OrganizationRoute
  '/tenant': typeof TenantRoute
  '/dsm/clients': typeof DsmClientsRoute
  '/dsm/cookbooks': typeof DsmCookbooksRoute
  '/dsm/data-bags': typeof DsmDataBagsRoute
  '/dsm/environments': typeof DsmEnvironmentsRoute
  '/dsm/policy-groups': typeof DsmPolicyGroupsRoute
  '/dsm/policyfiles': typeof DsmPolicyfilesRoute
  '/dsm/roles': typeof DsmRolesRoute
  '/nodes/activity': typeof NodesActivityRoute
  '/nodes/cohorts': typeof NodesCohortsRoute
  '/nodes/enroll': typeof NodesEnrollRoute
  '/nodes/settings': typeof NodesSettingsRoute
  '/nodes/skills': typeof NodesSkillsRoute
  '/nodes/': typeof NodesIndexRoute
  '/reporting/': typeof ReportingIndexRoute
  '/dsm/nodes/$nodeId': typeof DsmNodesNodeIdRoute
  '/nodes/detail/$nodeId': typeof NodesDetailNodeIdRoute
  '/reporting/client/$runId': typeof ReportingClientRunIdRoute
  '/reporting/inspec/$scanId': typeof ReportingInspecScanIdRoute
  '/reporting/node-management/$nodeId': typeof ReportingNodeManagementNodeIdRoute
  '/dsm/nodes/': typeof DsmNodesIndexRoute
  '/reporting/client/': typeof ReportingClientIndexRoute
  '/reporting/inspec/': typeof ReportingInspecIndexRoute
  '/reporting/node-management/': typeof ReportingNodeManagementIndexRoute
  '/reporting/inspec/profile/$profileId': typeof ReportingInspecProfileProfileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/courier'
    | '/downloads'
    | '/organization'
    | '/tenant'
    | '/dsm/clients'
    | '/dsm/cookbooks'
    | '/dsm/data-bags'
    | '/dsm/environments'
    | '/dsm/policy-groups'
    | '/dsm/policyfiles'
    | '/dsm/roles'
    | '/nodes/activity'
    | '/nodes/cohorts'
    | '/nodes/enroll'
    | '/nodes/settings'
    | '/nodes/skills'
    | '/nodes/'
    | '/reporting/'
    | '/dsm/nodes/$nodeId'
    | '/nodes/detail/$nodeId'
    | '/reporting/client/$runId'
    | '/reporting/inspec/$scanId'
    | '/reporting/node-management/$nodeId'
    | '/dsm/nodes/'
    | '/reporting/client/'
    | '/reporting/inspec/'
    | '/reporting/node-management/'
    | '/reporting/inspec/profile/$profileId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/courier'
    | '/downloads'
    | '/organization'
    | '/tenant'
    | '/dsm/clients'
    | '/dsm/cookbooks'
    | '/dsm/data-bags'
    | '/dsm/environments'
    | '/dsm/policy-groups'
    | '/dsm/policyfiles'
    | '/dsm/roles'
    | '/nodes/activity'
    | '/nodes/cohorts'
    | '/nodes/enroll'
    | '/nodes/settings'
    | '/nodes/skills'
    | '/nodes'
    | '/reporting'
    | '/dsm/nodes/$nodeId'
    | '/nodes/detail/$nodeId'
    | '/reporting/client/$runId'
    | '/reporting/inspec/$scanId'
    | '/reporting/node-management/$nodeId'
    | '/dsm/nodes'
    | '/reporting/client'
    | '/reporting/inspec'
    | '/reporting/node-management'
    | '/reporting/inspec/profile/$profileId'
  id:
    | '__root__'
    | '/'
    | '/courier'
    | '/downloads'
    | '/organization'
    | '/tenant'
    | '/dsm/clients'
    | '/dsm/cookbooks'
    | '/dsm/data-bags'
    | '/dsm/environments'
    | '/dsm/policy-groups'
    | '/dsm/policyfiles'
    | '/dsm/roles'
    | '/nodes/activity'
    | '/nodes/cohorts'
    | '/nodes/enroll'
    | '/nodes/settings'
    | '/nodes/skills'
    | '/nodes/'
    | '/reporting/'
    | '/dsm/nodes/$nodeId'
    | '/nodes/detail/$nodeId'
    | '/reporting/client/$runId'
    | '/reporting/inspec/$scanId'
    | '/reporting/node-management/$nodeId'
    | '/dsm/nodes/'
    | '/reporting/client/'
    | '/reporting/inspec/'
    | '/reporting/node-management/'
    | '/reporting/inspec/profile/$profileId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CourierRoute: typeof CourierRoute
  DownloadsRoute: typeof DownloadsRoute
  OrganizationRoute: typeof OrganizationRoute
  TenantRoute: typeof TenantRoute
  DsmClientsRoute: typeof DsmClientsRoute
  DsmCookbooksRoute: typeof DsmCookbooksRoute
  DsmDataBagsRoute: typeof DsmDataBagsRoute
  DsmEnvironmentsRoute: typeof DsmEnvironmentsRoute
  DsmPolicyGroupsRoute: typeof DsmPolicyGroupsRoute
  DsmPolicyfilesRoute: typeof DsmPolicyfilesRoute
  DsmRolesRoute: typeof DsmRolesRoute
  NodesActivityRoute: typeof NodesActivityRoute
  NodesCohortsRoute: typeof NodesCohortsRoute
  NodesEnrollRoute: typeof NodesEnrollRoute
  NodesSettingsRoute: typeof NodesSettingsRoute
  NodesSkillsRoute: typeof NodesSkillsRoute
  NodesIndexRoute: typeof NodesIndexRoute
  ReportingIndexRoute: typeof ReportingIndexRoute
  DsmNodesNodeIdRoute: typeof DsmNodesNodeIdRoute
  NodesDetailNodeIdRoute: typeof NodesDetailNodeIdRoute
  ReportingClientRunIdRoute: typeof ReportingClientRunIdRoute
  ReportingInspecScanIdRoute: typeof ReportingInspecScanIdRoute
  ReportingNodeManagementNodeIdRoute: typeof ReportingNodeManagementNodeIdRoute
  DsmNodesIndexRoute: typeof DsmNodesIndexRoute
  ReportingClientIndexRoute: typeof ReportingClientIndexRoute
  ReportingInspecIndexRoute: typeof ReportingInspecIndexRoute
  ReportingNodeManagementIndexRoute: typeof ReportingNodeManagementIndexRoute
  ReportingInspecProfileProfileIdRoute: typeof ReportingInspecProfileProfileIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courier': {
      id: '/courier'
      path: '/courier'
      fullPath: '/courier'
      preLoaderRoute: typeof CourierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization': {
      id: '/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof OrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant': {
      id: '/tenant'
      path: '/tenant'
      fullPath: '/tenant'
      preLoaderRoute: typeof TenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dsm/clients': {
      id: '/dsm/clients'
      path: '/dsm/clients'
      fullPath: '/dsm/clients'
      preLoaderRoute: typeof DsmClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dsm/cookbooks': {
      id: '/dsm/cookbooks'
      path: '/dsm/cookbooks'
      fullPath: '/dsm/cookbooks'
      preLoaderRoute: typeof DsmCookbooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dsm/data-bags': {
      id: '/dsm/data-bags'
      path: '/dsm/data-bags'
      fullPath: '/dsm/data-bags'
      preLoaderRoute: typeof DsmDataBagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dsm/environments': {
      id: '/dsm/environments'
      path: '/dsm/environments'
      fullPath: '/dsm/environments'
      preLoaderRoute: typeof DsmEnvironmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dsm/policy-groups': {
      id: '/dsm/policy-groups'
      path: '/dsm/policy-groups'
      fullPath: '/dsm/policy-groups'
      preLoaderRoute: typeof DsmPolicyGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dsm/policyfiles': {
      id: '/dsm/policyfiles'
      path: '/dsm/policyfiles'
      fullPath: '/dsm/policyfiles'
      preLoaderRoute: typeof DsmPolicyfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dsm/roles': {
      id: '/dsm/roles'
      path: '/dsm/roles'
      fullPath: '/dsm/roles'
      preLoaderRoute: typeof DsmRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes/': {
      id: '/nodes/'
      path: '/nodes'
      fullPath: '/nodes/'
      preLoaderRoute: typeof NodesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes/activity': {
      id: '/nodes/activity'
      path: '/nodes/activity'
      fullPath: '/nodes/activity'
      preLoaderRoute: typeof NodesActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes/cohorts': {
      id: '/nodes/cohorts'
      path: '/nodes/cohorts'
      fullPath: '/nodes/cohorts'
      preLoaderRoute: typeof NodesCohortsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes/enroll': {
      id: '/nodes/enroll'
      path: '/nodes/enroll'
      fullPath: '/nodes/enroll'
      preLoaderRoute: typeof NodesEnrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes/settings': {
      id: '/nodes/settings'
      path: '/nodes/settings'
      fullPath: '/nodes/settings'
      preLoaderRoute: typeof NodesSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes/skills': {
      id: '/nodes/skills'
      path: '/nodes/skills'
      fullPath: '/nodes/skills'
      preLoaderRoute: typeof NodesSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reporting/': {
      id: '/reporting/'
      path: '/reporting'
      fullPath: '/reporting/'
      preLoaderRoute: typeof ReportingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dsm/nodes/': {
      id: '/dsm/nodes/'
      path: '/dsm/nodes'
      fullPath: '/dsm/nodes/'
      preLoaderRoute: typeof DsmNodesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dsm/nodes/$nodeId': {
      id: '/dsm/nodes/$nodeId'
      path: '/dsm/nodes/$nodeId'
      fullPath: '/dsm/nodes/$nodeId'
      preLoaderRoute: typeof DsmNodesNodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes/detail/$nodeId': {
      id: '/nodes/detail/$nodeId'
      path: '/nodes/detail/$nodeId'
      fullPath: '/nodes/detail/$nodeId'
      preLoaderRoute: typeof NodesDetailNodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reporting/client/': {
      id: '/reporting/client/'
      path: '/reporting/client'
      fullPath: '/reporting/client/'
      preLoaderRoute: typeof ReportingClientIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reporting/client/$runId': {
      id: '/reporting/client/$runId'
      path: '/reporting/client/$runId'
      fullPath: '/reporting/client/$runId'
      preLoaderRoute: typeof ReportingClientRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reporting/inspec/': {
      id: '/reporting/inspec/'
      path: '/reporting/inspec'
      fullPath: '/reporting/inspec/'
      preLoaderRoute: typeof ReportingInspecIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reporting/inspec/$scanId': {
      id: '/reporting/inspec/$scanId'
      path: '/reporting/inspec/$scanId'
      fullPath: '/reporting/inspec/$scanId'
      preLoaderRoute: typeof ReportingInspecScanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reporting/node-management/': {
      id: '/reporting/node-management/'
      path: '/reporting/node-management'
      fullPath: '/reporting/node-management/'
      preLoaderRoute: typeof ReportingNodeManagementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reporting/node-management/$nodeId': {
      id: '/reporting/node-management/$nodeId'
      path: '/reporting/node-management/$nodeId'
      fullPath: '/reporting/node-management/$nodeId'
      preLoaderRoute: typeof ReportingNodeManagementNodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reporting/inspec/profile/$profileId': {
      id: '/reporting/inspec/profile/$profileId'
      path: '/reporting/inspec/profile/$profileId'
      fullPath: '/reporting/inspec/profile/$profileId'
      preLoaderRoute: typeof ReportingInspecProfileProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CourierRoute: CourierRoute,
  DownloadsRoute: DownloadsRoute,
  OrganizationRoute: OrganizationRoute,
  TenantRoute: TenantRoute,
  DsmClientsRoute: DsmClientsRoute,
  DsmCookbooksRoute: DsmCookbooksRoute,
  DsmDataBagsRoute: DsmDataBagsRoute,
  DsmEnvironmentsRoute: DsmEnvironmentsRoute,
  DsmPolicyGroupsRoute: DsmPolicyGroupsRoute,
  DsmPolicyfilesRoute: DsmPolicyfilesRoute,
  DsmRolesRoute: DsmRolesRoute,
  NodesActivityRoute: NodesActivityRoute,
  NodesCohortsRoute: NodesCohortsRoute,
  NodesEnrollRoute: NodesEnrollRoute,
  NodesSettingsRoute: NodesSettingsRoute,
  NodesSkillsRoute: NodesSkillsRoute,
  NodesIndexRoute: NodesIndexRoute,
  ReportingIndexRoute: ReportingIndexRoute,
  DsmNodesNodeIdRoute: DsmNodesNodeIdRoute,
  NodesDetailNodeIdRoute: NodesDetailNodeIdRoute,
  ReportingClientRunIdRoute: ReportingClientRunIdRoute,
  ReportingInspecScanIdRoute: ReportingInspecScanIdRoute,
  ReportingNodeManagementNodeIdRoute: ReportingNodeManagementNodeIdRoute,
  DsmNodesIndexRoute: DsmNodesIndexRoute,
  ReportingClientIndexRoute: ReportingClientIndexRoute,
  ReportingInspecIndexRoute: ReportingInspecIndexRoute,
  ReportingNodeManagementIndexRoute: ReportingNodeManagementIndexRoute,
  ReportingInspecProfileProfileIdRoute: ReportingInspecProfileProfileIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
declare module '@tanstack/react-router' {
  interface Register {
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
